### PR TITLE
AIDL interface that allows people to forward their terminal output to the app

### LINKED ISSUE #156: Window Handle issues
When requesting a window using RUN_SCRIPT, there is no way to compare the returned handle to any stored handle to ensure you link into the correct terminal window before launching the intent, making it incredibly difficult to ensure that the proper commands go to the proper window.

As a general security concern, window handles should never be stored anywhere in plain-text (or window hijacking can occur very easily), and constantly de/obfuscating returned handles to make them secure if stored takes 3x times as much computing as normal to just get a usable handle, and with the current implemented model, the result comes after the request, making it so you have to run your first script completely blind.

Wouldit be possible to make it so the calling app can pass a custom handle to ATE, allowing for an app to declare its own window, or to maybe implement the BroadcastReciever idea brought up in a previous feature request?

### PR DESCRIPTION
**Pull request by Alexander--**
Solves #381 
Solves #169 
More or less fixes #156 
Fixes #120 

This pull request aims to replace existing Intent-based interface for launching commands with AIDL-based API. The API uses Android/Linux ability to pass file descriptors between processes to grant ATE access to /dev/ptmx handle, created by someone else. In effect this means, that another program launches an executable (with it's own permissions), but leaves ATE in charge of showing it's console output.

The AIDL interface is more or less a draft. There is, probably, no way to do it right except by letting people use it a bit and gathering suggestions. Feel free to ask, if you want to know, why it looks this way.

I am personally interested in this for my [aria2 port](https://github.com/Alexander--/aria2-android). I will do my best to help with supporting the new code, as long as I am able to use it myself. You can look how an integration is done in [ate-support](https://github.com/Alexander--/aria2-android/tree/ate-support) branch or get [this build](https://github.com/Alexander--/aria2-android/releases/download/0.9.1.0-beta/net.sf.aria2-1.apk) to get a peek at preliminary implementation on device.

This PR introduces new library in addition to emulatorview. It is called libtermexec and contains AIDL files, native code and Java wrapper for launching binaries with inbuilt console support. It can be very useful on it's own to replace *java.lang.System* and *ProcessBuilder* for launching executable files (and gives access to the PID unlike those). The library in Android AAR format, with AIDL and native binaries included, can be published on Maven to let people use it readily without using NDK themselves.

This PR may have an impact on various parts of ATE. I tried to keep it minimal without refactoring unnecessary parts, other important changes may have to be done later, see below for details. Biggest changes done here are:

* Splittig ShellSession in few subclasses
* Changes to open /dev/ptmx in Java code and using ParcelFileDescriptor instead of digging integer fd out of FileDescriptor with Reflection. Some reflection still remains, but only on older versions. 

Perfomance considerations:

* Foreground mode probably should not be used unless necessary (e.g. don't go foreground when someone is still binding to the TermService). See also [this question](https://stackoverflow.com/q/6645193);
* There should probably be some form of window recycling to prevent single client from opening loads of windows in the "keep window open after session end" mode. Also valid for exesting _RUN_SCRIPT_-based API.

Security considerations:

* No need for permissions, because no work is done on ATE side besides displaying text from file.
* Someone can pass weird file descriptor (such as /dev/full or just some binary file) instead of /dev/ptmx handle to screw with emulator. Not exactly dangerous and can be mitigated by properly handling failures of native tty-related methods.
* May be abused to impersonate important windows, same as _RUN_SCRIPT_-based API. I didn't notice any defense there either. Can be mitigated by prepending name of originating app in title. This is already done in AIDL binder, but something seems to be wrong with whole "displaying window title thing", it just does not work for me.

Documentation considerations:

* Must tell people to use Context.BIND_AUTO_CREATE to prevent [restart](https://stackoverflow.com/q/10676204) of TermService upon unbind. Maybe there is a way to disallow binding without the flag. Alternatively TermService can keep itself alive with startService and do stopSelf only when necessary.

Hopefully, size and complexity of these changes won't stop you from reviewing them. If you'd rather look at iterative lineage of commits instead of single squashed one, see [this branch](https://github.com/Alexander--/Android-Terminal-Emulator/tree/new-api).

PS I have changed the language level to Java 7, because Java 6 is dead, and multi-catch and string-switch are too good to miss out on. This won't introduce any compatibility changes, unless you try to use try-block  resource management (aka try-with-resources), in which case the IDE will loudly warn you. I can roll that one back, if you don't want it.

### CODE REVIEW

**Comment by Alexander--** [comment]
By the way, I have finally dug out [source code](https://android.googlesource.com/platform/libcore/+/master/luni/src/main/native/java_lang_ProcessManager.cpp) of Android ProcessManager, and it does mass-closing of file descriptors after fork as advised by many sources. Shouldn't ATE do the same?

**Comment by jackpal** [comment]
Wow, thanks for the patch. It's going to take a while to understand it.

We tried mass-closing open file descriptors after fork, and it broke
networking. (example, ping did not work.) Apparently the bionic libraries
depend on some (undocumented) file descriptors remaining open across fork
in order to work.

I guess someone needs to do some research to figure out exactly which file
descriptors needed to be closed, vs left open. Or maybe patch bionic to
work correctly with fork and mass closing?

**Comment by Alexander--** [comment]
> Wow, thanks for the patch. It's going to take a while to understand it.

Feel free to comment on parts, that seem unclear. Alternatively, I can try to split it in isolated parts and do a quick review of those (not that it would be much shorter, compared to patch itself, sigh)

>  guess someone needs to do some research to figure out exactly which file descriptors needed to be closed, vs left open.

Have you seen the code I linked to in my comment? From quick glance, it seems, that `ANDROID_PROPERTY_WORKSPACE` may be a key to said descriptor(s). Still not sure, if mass-closing is a good idea in first place. Do open descriptors even affect chances of being killed by low memory killer? And what if some version of Android introduces more of said descriptors? Maybe, there should be some kind of sanity-check to ensure, that behavior is same as known — when the check detects, that descriptor from `ANDROID_PROPERTY_WORKSPACE` is unused or more descriptors remain open after using `ProcessBuilder`, descriptors cleanup step is skipped...

**Comment by jackpal** [comment]
I should clarify that I think it's OK to update the compiler version to 12 in order to conditionally access the API level 12 API. But I want the app to continue to run on SDK 3. (It's true that SDK 4 is required to access the Play Market, but dedicated Cupcake users can still side load the app.)

I am thinking of updating the Min-SDK to 7 in a few months, but that is because I want to use the app compat library for Material Design.

**Comment by Alexander--** [comment]
I have amended the commit to use the backward compatibility technique you mentioned. Sorry, I haven't written code for pre-9 API for a long time, so that slipped in.

**Comment by jackpal** [comment]
Thanks! Unfortunately, the new patch still fails at launch on API 4, with this stack crawl

3-15 16:10:36.313      241-241/jackpal.androidterm I/libjackpal-androidterm﹕ JNI_OnLoad
03-15 16:10:36.393      241-241/jackpal.androidterm E/dalvikvm﹕ Could not find method java.lang.ReflectiveOperationException.getLocalizedMessage, referenced from method jackpal.androidterm.TermExec.createSubprocess
03-15 16:10:36.403      241-241/jackpal.androidterm W/dalvikvm﹕ VFY: unable to resolve virtual method 1676: Ljava/lang/ReflectiveOperationException;.getLocalizedMessage ()Ljava/lang/String;
03-15 16:10:36.403      241-241/jackpal.androidterm W/dalvikvm﹕ VFY:  rejecting opcode 0x6e at 0x003c
03-15 16:10:36.403      241-241/jackpal.androidterm W/dalvikvm﹕ VFY:  rejected Ljackpal/androidterm/TermExec;.createSubprocess (Landroid/os/ParcelFileDescriptor;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)I
03-15 16:10:36.403      241-241/jackpal.androidterm W/dalvikvm﹕ Verifier rejected class Ljackpal/androidterm/TermExec;
03-15 16:10:36.403      241-241/jackpal.androidterm D/AndroidRuntime﹕ Shutting down VM
03-15 16:10:36.403      241-241/jackpal.androidterm W/dalvikvm﹕ threadid=3: thread exiting with uncaught exception (group=0x4001aa28)
03-15 16:10:36.403      241-241/jackpal.androidterm E/AndroidRuntime﹕ Uncaught handler: thread main exiting due to uncaught exception
03-15 16:10:36.473      241-241/jackpal.androidterm E/AndroidRuntime﹕ java.lang.VerifyError: jackpal.androidterm.TermExec
            at jackpal.androidterm.ShellTermSession.createSubprocess(ShellTermSession.java:153)
            at jackpal.androidterm.ShellTermSession.initializeSession(ShellTermSession.java:101)
            at jackpal.androidterm.ShellTermSession.<init>(ShellTermSession.java:57)
            at jackpal.androidterm.Term.createTermSession(Term.java:502)
            at jackpal.androidterm.Term.createTermSession(Term.java:511)
            at jackpal.androidterm.Term.populateViewFlipper(Term.java:418)
            at jackpal.androidterm.Term.access$400(Term.java:82)
            at jackpal.androidterm.Term$2.onServiceConnected(Term.java:152)
            at android.app.ActivityThread$PackageInfo$ServiceDispatcher.doConnected(ActivityThread.java:1053)
            at android.app.ActivityThread$PackageInfo$ServiceDispatcher$RunConnection.run(ActivityThread.java:1070)
            at android.os.Handler.handleCallback(Handler.java:587)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:123)
            at android.app.ActivityThread.main(ActivityThread.java:4203)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:521)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by jackpal** [comment]
OK, fine, let's bump MinSDK to API level 10 (2.3.7 aka Gingerbread). I'll leave the current version in the store for users with older versions of Android.

**Comment by Alexander--** [comment]
No need, this one should work. If there are more issues, I will get hands on API v4 device or install emulator and debug them ASAP. It is better to avoid raising requirements when introducing this kind of changes in external API, or else adoption rate of those changes may suffer.

**Comment by jackpal** [comment]
OK, if you want to keep trying for API level 4, the next error is:

03-15 17:14:48.788      214-214/jackpal.androidterm D/dalvikvm﹕ Added
shared lib /data/data/jackpal.androidterm/lib/libjackpal-androidterm4.so
0x4376b220
03-15 17:14:48.788      214-214/jackpal.androidterm
I/libjackpal-androidterm﹕ JNI_OnLoad
03-15 17:14:48.848      214-214/jackpal.androidterm E/dalvikvm﹕ Could not
find method java.lang.ReflectiveOperationException.getMessage, referenced
from method jackpal.androidterm.TermExec.createSubprocess
03-15 17:14:48.858      214-214/jackpal.androidterm W/dalvikvm﹕ VFY: unable
to resolve virtual method 1676:
Ljava/lang/ReflectiveOperationException;.getMessage ()Ljava/lang/String;
03-15 17:14:48.858      214-214/jackpal.androidterm W/dalvikvm﹕ VFY:
 rejecting opcode 0x6e at 0x003c
03-15 17:14:48.858      214-214/jackpal.androidterm W/dalvikvm﹕ VFY:
 rejected Ljackpal/androidterm/TermExec;.createSubprocess
(Landroid/os/ParcelFileDescriptor;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)I
03-15 17:14:48.858      214-214/jackpal.androidterm W/dalvikvm﹕ Verifier
rejected class Ljackpal/androidterm/TermExec;
03-15 17:14:48.858      214-214/jackpal.androidterm D/AndroidRuntime﹕
Shutting down VM
03-15 17:14:48.868      214-214/jackpal.androidterm W/dalvikvm﹕ threadid=3:
thread exiting with uncaught exception (group=0x4001aa28)
03-15 17:14:48.868      214-214/jackpal.androidterm E/AndroidRuntime﹕
Uncaught handler: thread main exiting due to uncaught exception
03-15 17:14:48.928      214-214/jackpal.androidterm E/AndroidRuntime﹕
java.lang.VerifyError: jackpal.androidterm.TermExec
            at
jackpal.androidterm.ShellTermSession.createSubprocess(ShellTermSession.java:153)
            at
jackpal.androidterm.ShellTermSession.initializeSession(ShellTermSession.java:101)
            at
jackpal.androidterm.ShellTermSession.<init>(ShellTermSession.java:57)
            at jackpal.androidterm.Term.createTermSession(Term.java:502)
            at jackpal.androidterm.Term.createTermSession(Term.java:511)
            at jackpal.androidterm.Term.populateViewFlipper(Term.java:418)
            at jackpal.androidterm.Term.access$400(Term.java:82)
            at jackpal.androidterm.Term$2.onServiceConnected(Term.java:152)
            at
android.app.ActivityThread$PackageInfo$ServiceDispatcher.doConnected(ActivityThread.java:1053)
            at
android.app.ActivityThread$PackageInfo$ServiceDispatcher$RunConnection.run(ActivityThread.java:1070)
            at android.os.Handler.handleCallback(Handler.java:587)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:123)
            at android.app.ActivityThread.main(ActivityThread.java:4203)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:521)
            at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
            at dalvik.system.NativeStart.main(Native Method)
03-15 17:14:48.988      214-217/jackpal.androidterm I/dalvikvm﹕ threadid=7:
reacting to signal 3
03-15 17:14:48.988      214-217/jackpal.androidterm E/dalvikvm﹕ Unable to
open stack trace file '/data/anr/traces.txt': Permission denied

**Comment by Alexander--** [comment]
As promised, here is a version, tested on Donut. No testing, related to this PR was done, but at least the ATE works.

**Comment by Alexander--** [comment]
Have there been any progress with this? Should I, perhaps, suggest people to download a customized version of ATE while it is being merged?

**Comment by jackpal** [comment]
Sorry, was busy with work and other projects. I'll look at merging this today.

**Comment by jackpal** [comment]
I opened issue #399 to track fixing file-descriptor-close-when-forking.

**Pull request merged**
